use_frameworks!

platform :ios, '9.0'

target 'circularContohFramework_Example' do
  pod 'circularContohFramework', :path => '../'

  target 'circularContohFramework_Tests' do
    inherit! :search_paths

    
  end
end
